<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBanTranh" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-R57SVSA\SQLEXPRESS;Initial Catalog=QuanLyBanTranh;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyBanTranhConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANH" Member="TRANHs">
    <Type Name="TRANH">
      <Column Name="MATRANH" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTRANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BAOHANH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ANHBIA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MACD" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Association Name="TRANH_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MATRANH" OtherKey="MATRANH" Type="CHITIETDONHANG" />
      <Association Name="CHUDE_TRANH" Member="CHUDE" ThisKey="MACD" OtherKey="MACD" Type="CHUDE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONHANG" Member="CHITIETDONHANGs">
    <Type Name="CHITIETDONHANG">
      <Column Name="MADH" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATRANH" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="TRANH_CHITIETDONHANG" Member="TRANH" ThisKey="MATRANH" OtherKey="MATRANH" Type="TRANH" IsForeignKey="true" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="DONHANG" ThisKey="MADH" OtherKey="MADH" Type="DONHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MACD" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHUDE_TRANH" Member="TRANHs" ThisKey="MACD" OtherKey="MACD" Type="TRANH" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MADH" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATHANHTOAN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MADH" OtherKey="MADH" Type="CHITIETDONHANG" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TAIKHOAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONHANG" />
    </Type>
  </Table>
</Database>